### PR TITLE
parseFeedString allows custom parsing function

### PR DESCRIPTION
**Pull request by aaronlevin**
I was using your library to read the feed `http://weirdcanada.com/feed`. The feed wasn't parsing (not sure why still), so I wanted to be able to pass in my own function from `String -> Element` for `parseFeedString`.

No behaviour was changed. I added a new method `parseFeedWithCustomparser`. 

PS - if you have any insight into why that url isn't parsing that would be great. I validated the xml and it checked. I think it may be related to the CDATA.

### CODE REVIEW

**Comment by sof** [comment]
Looks just fine, merged.

A temporary publication problem with the feed? Parses fine for me now.

**Comment by aaronlevin** [comment]
Hmm, perhaps there was some malignant code that was breaking out of the
CDATA? If you don't mind trying: http://silentshout.ca/feed/ ? That one was
also failing.

Thank you!

On Mon, Aug 5, 2013 at 4:43 AM, sof notifications@github.com wrote:

> Looks just fine, merged.
> 
> A temporary publication problem with the feed? Parses fine for me now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sof/feed/pull/1#issuecomment-22093479
> .

## 

Aaron Levin / Weird Canada
www.aaronlevin.ca / www.weirdcanada.com

**Comment by sof** [comment]
That's fine (*) for me also. Seems like your problem might lie elsewhere

--sigbjorn
- \- steps followed:

foo$ cd tests
foo$ ghc -o main Main.hs -package feed
foo$ curl -L -o sample.rss http://silentshout.ca/feed/
foo$ ./main sample.rss
...pretty-printed version of feed...
foo$ 

(same thing verified to happen if you don't use the UTF-8 savvy version of readFile. This is with xml-1.3.13)

**Comment by aaronlevin** [comment]
Thanks for the tip. There's french-Canadian characters in those feeds so
I'll make sure whatever code is downloading the stream is ensuring unicode
characters aren't getting garbled.

Thanks again.

On Mon, Aug 5, 2013 at 12:26 PM, sof notifications@github.com wrote:

> That's fine (*) for me also. Seems like your problem might lie elsewhere
> 
> --sigbjorn
> - \- steps followed:
> 
> foo$ cd tests
> foo$ ghc -o main Main.hs -package feed
> foo$ curl -L -o sample.rss http://silentshout.ca/feed/
> foo$ ./main sample.rss
> ...pretty-printed version of feed...
> foo$
> 
> (same thing verified to happen if you don't use the UTF-8 savvy version of
> readFile. This is with xml-1.3.13)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sof/feed/pull/1#issuecomment-22117892
> .

## 

Aaron Levin / Weird Canada
www.aaronlevin.ca / www.weirdcanada.com

**Pull request merged**
